### ISSUE TITLE
RedFish support

### ISSUE THREAD

**Issue by mmaymann** [tinkerbell/proposals#68]
https://github.com/DMTF

https://github.com/sonic-net/SONiC/issues/1362

**Comment by chrisdoherty4** [comment]
Hi @mmaymann. We have Refish support already in PBnJ and Rufio, our BMC components. Are you experiencing gaps in the existing integration?

**Comment by mmaymann** [comment]
Sounds really good - thanks for links 😊

**Comment by FruityWelsh** [comment]
Could this issue be reopened for redfish support as a boot target (for authenticated/encrypted boot support)?

Bios/firmware management would also be useful items for bare metal management.
